### ISSUE TITLE
Wrong path in build script for 'libSkiaSharp.a'

### ISSUE THREAD

**Issue by ZeProgFactory** [unoplatform/Uno.Wasm.Bootstrap#323] opened 2021-01-06 00:28 UTC
When building a WASM project on CS2019 on Windows 10 Pro I get:
```
ninja: error: '/mnt/c/Users/zepro/.nuget/packages/uno.skiasharp.wasm/2.80.0-uno.483/build/netstandard2.0/libSkia/libSkiaSharp.a', needed by '/mnt/d/GitWare/Apps/StoreCheck/Sources/StoreCheck.Client/StoreCheck.Client.Wasm/obj/Debug/netstandard2.1/dist_work/dotnet.js', missing and no known rule to make it
```
on my computer the path is

```
C:\Users\zepro\.nuget\packages\uno.skiasharp.wasm\2.80.0-uno.483\build\libSkia
```
The ```libSkia``` is beside ```netstandard2.1``` and not under it.

# Workaround and new problem (for me)
Coping the lib to the expected path will pass this step, but the compilation ends
with ``` error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch) ``` .
Is there a way to deactivate the use of AOT layout?

# Packages context
```
      <PackageReference Include="Uno.SkiaSharp.Views" Version="2.80.0-uno.483" />
      <PackageReference Include="Uno.SkiaSharp.Wasm" Version="2.80.0-uno.483" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.2" />
      <PackageReference Include="Uno.UI.WebAssembly" Version="3.4.0" />
      <PackageReference Include="Uno.UI.RemoteControl" Version="3.4.0" Condition="'$(Configuration)'=='Debug'" />
      <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.3.6" />
      <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.3.6" />
```

**Comment by jeromelaban** [comment] 2021-01-06 02:23
Thanks for the report. This issue has been fixed in build `2.80.0-uno.490` of Uno.SkiaSharp.

Try updating and let us know if this helps.

**Comment by ZeProgFactory** [comment] 2021-01-06 03:20
Yes the path issue is solved with the preview build ```2.80.0-uno.490``` of Uno.SkiaSharp!

But the secondary problem is still there:
```
3>Downloading mono-wasm-f30f5adfbbb to C:\Users\zepro\AppData\Local\Temp\mono-wasm-f30f5adfbbb.aot.zip
3>C:\Users\zepro\.nuget\packages\uno.wasm.bootstrap\2.0.0-dev.125\build\Uno.Wasm.Bootstrap.targets(171,2): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
3>C:\Users\zepro\.nuget\packages\uno.wasm.bootstrap\2.0.0-dev.125\build\Uno.Wasm.Bootstrap.targets(171,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v771c83950ec40b1b52bb70924ca618b609025f9c.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 736
3>C:\Users\zepro\.nuget\packages\uno.wasm.bootstrap\2.0.0-dev.125\build\Uno.Wasm.Bootstrap.targets(171,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v771c83950ec40b1b52bb70924ca618b609025f9c.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 210
```
Is there a way to deactivate the use of AOT layout (I already tried some settings without success)?

**Comment by jeromelaban** [comment] 2021-01-06 03:27
In the context of skia, the issue is not related to AOT (contrary to the error messages), but the use of emscripten. It is required to be executed when using Skia.

To troubleshoot this, set your msbuild logging level to "Normal", you'll get more information.

**Comment by jeromelaban** [comment] 2021-02-09 02:09
This issue has been fixed in recent build of SkiaSharp.

**Closed by jeromelaban** 2021-02-09 02:09 UTC
